smtp_on: 0
smtp_host: ''
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: 'standard'
smtp_username: ''
smtp_password: ''
smtp_from: ''
smtp_fromname: ''
smtp_allowhtml: ''
smtp_test_address: ''
smtp_debugging: 0
